#### Naive Bayes Classification Model

In [1]:
#Importing the libraries  
import numpy as np 
import matplotlib.pyplot as mtp  
import pandas as pd  

In [2]:
data = pd.read_csv('Iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# Define dependent and independent variables.
X = data.iloc[:, 1:5].values
y = data.iloc[:, 5].values
X.shape, y.shape

((150, 4), (150,))

In [5]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [6]:
# perform Feature Scaling if required
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [7]:
# Fitting Naive Bayes to the Training set 

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [8]:
# Predicting the Test set results  

y_pred = classifier.predict(X_test)  

In [9]:
df = pd.DataFrame({"Actual":y_test,"Predicted":y_pred})

In [10]:
df.head(5)

Actual        Predicted
0   Iris-virginica   Iris-virginica
1  Iris-versicolor  Iris-versicolor
2      Iris-setosa      Iris-setosa
3   Iris-virginica   Iris-virginica
4      Iris-setosa      Iris-setosa

In [11]:
# Analyse the predicted output using confusion matrics
from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix : \n", cm)
# sns.heatmap(cm, annot=True)

Confusion Matrix : 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [12]:
# Accuracy Score
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)*100
print("Accuracy Score = ",ac)

Accuracy Score =  96.66666666666667


In [13]:
# Predict the output for any one new input.
new_input = np.array([[2.1, 3.5, 0.5, 0.2]])
new_input_pred = classifier.predict(new_input)
print("Predicted Output : ", new_input_pred)

Predicted Output :  ['Iris-virginica']
